/**
 * Voice vocabulary - the shared types for the assistant page.
 *
 * `VoiceSession` (see `session.tsx`) is the state and action contract rendered by
 * the assistant page. The live implementation is in `echoflow.tsx`; this file
 * only defines the shared types.
 *
 * The `VoiceTransport` interface further down is an OPTIONAL contract for the
 * optional contract for a speech-to-speech engine (mic ownership, turn-taking,
 * barge-in, and event order). The current provider implements the FastAPI
 * WebSocket protocol directly instead of using this abstraction.
 *
 * Where to plug in: `src/voice/README.md`.
 *
 * ## Conventions the UI assumes (whatever engine you write)
 *
 * - The microphone `MediaStream` is owned by ONE place (your provider) and stopped
 *   there. The page never touches it.
 * - `turns[].text` is always the FULL text so far for that turn, never a delta.
 * - Only one phase is active at a time; mute, captions and volume are independent
 *   flags, not phases.
 * - Real backends are messy. The page tolerates phases that skip, repeat or
 *   arrive late, but it is designed around the documented order.
 *
 * @module
 */

// ---------------------------------------------------------------------------
// Phases, permission, connection
// ---------------------------------------------------------------------------

/**
 * Where the conversation is, as the UI should present it. Exactly one at a time.
 *
 * Happy path: `idle -> requesting-mic -> connecting -> listening <-> user-speaking
 * -> thinking -> speaking -> listening ...`, finished by `ended`. `reconnecting`
 * and `error` can interrupt any live phase.
 *
 * Mute, push-to-talk, captions and volume are NOT phases - they are independent
 * flags that can change in any phase.
 */
export type VoicePhase =
  /** Nothing running. The mic is off and no connection exists. Also the state after `reset()` and after a call that was cancelled before it went live. */
  | 'idle'
  /** `getUserMedia` is pending (the browser may be showing its permission prompt). */
  | 'requesting-mic'
  /** Mic acquired; `transport.connect()` is in flight. */
  | 'connecting'
  /** Live and waiting for the person to speak. The assistant is silent. */
  | 'listening'
  /** The person is speaking (server-detected or local). */
  | 'user-speaking'
  /** The person finished; the assistant has not started speaking yet. */
  | 'thinking'
  /** The assistant is speaking. Barge-in is possible. */
  | 'speaking'
  /** The connection dropped and is being recovered (or the mic device is being switched). */
  | 'reconnecting'
  /** The call is over (by the user, the remote side, a timeout, or the page being hidden). The transcript is still available. */
  | 'ended'
  /** The call failed. See `VoiceState.error`. Mic and transport are already released. */
  | 'error'

/**
 * What we know about the browser's microphone permission for this site.
 * Checking it never opens a prompt - only an explicit Start does.
 */
export type MicPermission =
  /** Not determined yet, or the Permissions API cannot tell (e.g. some browsers do not expose the microphone permission). */
  | 'unknown'
  /** The browser will ask when the person presses Start. */
  | 'prompt'
  /** Allowed. */
  | 'granted'
  /** Blocked. The person must re-enable it in browser/site settings; show browser-specific help. */
  | 'denied'
  /** No microphone was found on the device. */
  | 'no-device'
  /** A microphone exists but could not be opened (in use by another app, or a hardware/OS problem). */
  | 'busy'
  /** The page is not a secure context (plain http on a non-localhost host), so browsers hide the microphone API. */
  | 'insecure-context'
  /** The browser has no microphone capture API at all. */
  | 'unsupported'

/**
 * State of the link between the page and the assistant service.
 * Advisory and orthogonal to `VoicePhase`; drives the small connection chip.
 */
export type ConnectionState = 'offline' | 'connecting' | 'online' | 'reconnecting'

// ---------------------------------------------------------------------------
// Transcript
// ---------------------------------------------------------------------------

/**
 * One entry in the conversation. Immutable - the reducer replaces turns rather
 * than mutating them, so it is safe to use as React state / memo input.
 */
export interface TranscriptTurn {
  /**
   * Stable, opaque key for this turn (safe as a React `key`). Generated by the
   * reducer and NOT equal to the transport's `turnId`; it never changes, even
   * when the transport's transcript arrives later.
   */
  readonly id: string
  readonly role: 'user' | 'assistant'
  /**
   * The text so far. `''` is valid and common: a voice turn has empty text
   * while transcription is pending, and stays empty when transcription is not
   * available (the preview transport does this honestly - it cannot transcribe).
   * UIs should render an empty voice turn as "voice message", not as a blank.
   */
  readonly text: string
  /** `false` while the turn is still being spoken / transcribed, `true` once complete. Never goes back to `false`. */
  readonly final: boolean
  /** Epoch milliseconds (`Date.now()`) at which the turn began. */
  readonly at: number
  /** How the turn was produced: spoken aloud, or typed into the message box. */
  readonly via: 'voice' | 'text'
  /** Length of the person's speech in milliseconds (voice turns only). May be absent while the turn is open. */
  readonly speechMs?: number
  /** `true` on an assistant turn that was cut off (barge-in, Stop talking, connection loss, call ended mid-sentence). */
  readonly interrupted?: boolean
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/**
 * Why a call failed. Raised by the hook for `mic-*`, `insecure-context` and
 * `unsupported`; transports normally use `connection-failed`, `connection-lost`
 * or `transport-error`.
 */
export type VoiceErrorCode =
  /** The person (or a policy) blocked microphone access. */
  | 'mic-denied'
  /** No microphone on this device. */
  | 'mic-no-device'
  /** The microphone exists but is in use / cannot be opened. */
  | 'mic-busy'
  /** The microphone was working and then disappeared mid-call (unplugged, permission revoked). */
  | 'mic-lost'
  /** The page is not a secure context, so the browser hides the microphone API. */
  | 'insecure-context'
  /** The browser lacks a required capability. Not recoverable in this browser. */
  | 'unsupported'
  /** The first connection to the assistant service could not be established. */
  | 'connection-failed'
  /** An established connection dropped and could not be recovered. */
  | 'connection-lost'
  /** Any other failure inside the transport. */
  | 'transport-error'

/** A failure the UI can explain. `message` is calm, plain language and safe to show as-is. */
export interface VoiceError {
  readonly code: VoiceErrorCode
  /** Plain-language explanation, suitable for direct display and for screen readers. */
  readonly message: string
  /** `true` if pressing "Try again" can plausibly succeed. `false` means do not offer a retry (e.g. unsupported browser). */
  readonly recoverable: boolean
}

/** Why a call ended. */
export type VoiceEndReason =
  /** The person pressed End (hook-owned; transports never report this). */
  | 'user'
  /** The other side hung up. Transports report this. */
  | 'remote'
  /** A session limit or idle timeout was reached. Transports report this. */
  | 'timeout'
  /** The page was hidden/unloaded (`pagehide`), so the call was torn down (hook-owned). */
  | 'page-hidden'

// ---------------------------------------------------------------------------
// Session configuration and transport contract
// ---------------------------------------------------------------------------

/** Options the page passes to the transport when a call starts. */
export interface VoiceSessionConfig {
  /** BCP 47 language tag, e.g. `'en-IN'`. Used for speech recognition / voice choice. */
  locale: string
  /** Opaque voice identifier. `'default'` means "let the service choose". */
  voiceId: string
  /** The microphone the person picked, if any (informational - the stream you receive is already from that device). */
  inputDeviceId?: string
  /**
   * `false` when the page asks that speaking over the assistant must NOT
   * interrupt it. Advisory for `serverVad` transports (map it to your service's
   * interruption setting); the hook enforces it itself for local barge-in.
   * Absent / `true` = barge-in allowed.
   */
  bargeIn?: boolean
}

/** What a transport can do. The UI adapts to these flags rather than to transport names. */
export interface VoiceTransportCapabilities {
  /**
   * `true`: the transport detects start/end of the person's speech and handles
   * interruption itself, and will call `onUserSpeechStart` / `onUserSpeechEnd`.
   * `false`: the hook detects speech locally and drives turn-taking and barge-in.
   */
  serverVad: boolean
  /** `true`: `onUserTranscript` / `onAssistantTranscript` are called with interim (`final:false`) text. The UI streams captions word by word. `false`: only final text arrives. */
  partialTranscripts: boolean
  /** `true`: the transport reports assistant loudness (`onOutputLevel` or `getOutputLevel`) so visuals can react to it. */
  outputLevel: boolean
  /** `true`: `sendText` works. `false`: the UI hides the typed-message box. */
  textInput: boolean
}

/** A transcript update. `text` is ALWAYS the full text so far for that turn, never a delta. */
export interface TranscriptUpdate {
  /**
   * The FULL text of the turn so far. Applying the same update twice, or an
   * older update after a newer one, is harmless: the reducer replaces the text.
   * (A `final:false` update can never un-finalise a turn that is already final.)
   */
  text: string
  /** `true` exactly once, when the text will not change any more. */
  final: boolean
  /**
   * Stable id of the utterance in YOUR system (item id, response id...).
   * Provide it whenever you have one: it is what lets a late transcript land on
   * the right turn even after newer turns began. If omitted, the update applies
   * to the turn currently in progress for that speaker.
   */
  turnId?: string
}

/** A transcript update for the person's speech. */
export interface UserTranscriptUpdate extends TranscriptUpdate {
  /**
   * Length of the person's speech in ms, if your service knows it more exactly
   * than the page can (server VAD timestamps). If omitted the hook measures it
   * between speech-start and speech-end.
   */
  speechMs?: number
}

/**
 * Callbacks the TRANSPORT calls to tell the page what is happening.
 *
 * - All callbacks are safe to call at any time, from any task, synchronously or
 *   asynchronously; calls after `disconnect()` are ignored.
 * - They are idempotent: duplicate calls do no harm.
 * - Expected order within one exchange is listed on each callback.
 */
export interface VoiceTransportEvents {
  /**
   * The session is live and ready for audio. Call once after the connection is
   * established (before or as `connect()` resolves). Moves the UI `connecting ->
   * listening`. After a reconnect, `onConnectionState('online')` is enough.
   */
  onConnected: () => void
  /**
   * Link health changed. Call `'reconnecting'` (or `'offline'`) when the link
   * drops and you are recovering by yourself, and `'online'` when back - the UI
   * shows a "reconnecting" state and resumes `listening` (any turn in progress
   * is closed). If you give up, call `onError({code:'connection-lost'})`. The
   * hook also enforces a timeout on `reconnecting`.
   */
  onConnectionState: (state: ConnectionState) => void
  /** (serverVad) The person began speaking. Then zero or more `onUserTranscript` interims, then `onUserSpeechEnd`. */
  onUserSpeechStart: () => void
  /** (serverVad) The person stopped speaking. Normally followed by the final `onUserTranscript`, then `onThinking`. */
  onUserSpeechEnd: () => void
  /**
   * Text for the person's speech. May arrive late (after `onThinking` or even
   * after the assistant started speaking) - pass `turnId` so it lands on the
   * right turn. Call with `{text:'', final:true}` if you cannot transcribe, so
   * the turn closes cleanly.
   */
  onUserTranscript: (update: UserTranscriptUpdate) => void
  /** The assistant is preparing a reply (after the person finished, before any audio). Optional; ignored once speaking has begun. */
  onThinking: () => void
  /** The first assistant audio is about to be heard. Moves the UI to `speaking`. */
  onAssistantSpeechStart: () => void
  /** Text for the assistant's speech - the FULL text so far (never a delta), ideally in step with the audio. */
  onAssistantTranscript: (update: TranscriptUpdate) => void
  /**
   * Current assistant loudness, 0..1 (how loud it is being played, after any
   * volume scaling). Call at roughly 20-60 Hz while speaking; the page smooths
   * it. Alternatively implement `getOutputLevel()` and skip this.
   */
  onOutputLevel: (level: number) => void
  /**
   * The assistant stopped. `'complete'`: it finished its reply. `'interrupted'`:
   * it was cut off (barge-in or `interrupt()`). Always call it, including after
   * `interrupt()`, once playback has actually stopped.
   */
  onAssistantSpeechEnd: (reason: 'complete' | 'interrupted') => void
  /**
   * A FATAL failure. The hook releases the mic and the transport and shows the
   * error state; the person can retry when `recoverable`. For a problem you can
   * recover from yourself, use `onConnectionState('reconnecting')` instead.
   */
  onError: (error: VoiceError) => void
  /** The call ended from the service's side (`'remote'` or `'timeout'`). The hook releases everything. */
  onEnded: (reason: VoiceEndReason) => void
}

/** What `connect()` receives. */
export interface VoiceTransportConnectArgs {
  /**
   * The microphone stream, already acquired with echo cancellation, noise
   * suppression and auto gain on. OWNED BY THE HOOK: read or send from it, but
   * never stop its tracks or request another stream. `null` means a text-only
   * session (the person could not or chose not to use a mic): do not attach audio.
   */
  stream: MediaStream | null
  config: VoiceSessionConfig
  /**
   * Aborted if the page abandons this attempt (End pressed, unmount, a newer
   * session started). Stop connecting and reject promptly; any result you
   * produce afterwards is discarded.
   */
  signal: AbortSignal
}

/**
 * The single seam between this front end and a speech-to-speech backend.
 * Implement it, pass it to `<VoiceProvider transport={...}>`, done.
 *
 * Lifecycle: `connect()` once -> calls on the methods below -> `disconnect()`.
 * A transport instance may be reused for a later session; after `disconnect()`
 * it must be ready to `connect()` again. One session at a time.
 */
export interface VoiceTransport {
  /** Stable machine id, e.g. `'preview'`. */
  readonly id: string
  /** Short human label for badges, e.g. `'Preview'`. */
  readonly label: string
  /**
   * `true` only for the built-in scripted preview. While `true` the UI shows the
   * "Preview - no AI connected" honesty badge. A real transport sets `false`.
   */
  readonly isPreview: boolean
  readonly capabilities: VoiceTransportCapabilities

  /**
   * Establish the session. Resolve once it is usable (and call
   * `events.onConnected()` no later than resolving). Reject with a `VoiceError`
   * (or any `Error`, which becomes `connection-failed`) if it cannot connect, or
   * with an `AbortError` if `args.signal` aborted. Keep `events` for the
   * lifetime of this connection.
   */
  connect(args: VoiceTransportConnectArgs, events: VoiceTransportEvents): Promise<void>

  /**
   * Tear the session down and stop all playback/timers. IDEMPOTENT: may be called
   * any number of times, before, during or after connect, and must not throw.
   * MUST NOT stop the mic tracks - the hook owns them. Do not call events
   * after this returns.
   */
  disconnect(): Promise<void> | void

  /**
   * The person's microphone is (un)muted - explicit mute, or push-to-talk not
   * held. Stop sending audio (the hook also disables the track) and do not treat
   * silence as a turn. The assistant keeps speaking while muted. May be called
   * any time after `connect()` was invoked; remember the value and apply it.
   */
  setMuted(muted: boolean): void

  /**
   * Stop the assistant right now (barge-in, or the "Stop talking" button): cut
   * playback, flush queued audio, cancel the pending response. Afterwards call
   * `onAssistantSpeechEnd('interrupted')` once playback has actually stopped.
   * Harmless when nothing is playing.
   */
  interrupt(): void

  /**
   * Deliver a typed message from the person (only used if
   * `capabilities.textInput`). The hook has ALREADY added the user's turn to the
   * transcript - do not report it back. Respond as you would to speech:
   * `onThinking`, then the assistant events. If the assistant is speaking, treat
   * it as an interruption. Throw (or call `onError`) if it cannot be delivered.
   */
  sendText(text: string): void

  /** Output volume 0..1 for assistant audio. Remember it and apply it to current and future audio. */
  setOutputVolume(volume: number): void

  /**
   * (serverVad === false) The page's local detector believes the person started
   * (`true`) or stopped (`false`) speaking. On `false`, `detail.speechMs` is the
   * voiced duration. Use it to commit your audio buffer / start the reply; on
   * `true` while a reply is pending, cancel it - the person is still talking.
   * Not called when `capabilities.serverVad` is true, nor while muted.
   */
  hintLocalSpeech?(speaking: boolean, detail?: { speechMs: number }): void

  /**
   * Assistant loudness 0..1, polled by the page once per animation frame while
   * visuals are subscribed. Optional alternative to `onOutputLevel`.
   */
  getOutputLevel?(): number

  /**
   * Called synchronously inside the Start click handler, before anything is
   * awaited - the only moment a user gesture is guaranteed. Use it to unlock
   * audio playback that browsers gate behind a gesture (iOS Safari, autoplay
   * policies): resume your AudioContext, prime an `<audio>` element, etc.
   * Must not throw or block.
   */
  unlock?(): void
}

/** The part of a transport that UI code may read (label, honesty badge, feature flags). */
export type VoiceTransportInfo = Pick<VoiceTransport, 'id' | 'label' | 'isPreview' | 'capabilities'>
